### ISSUE TITLE
loadp2 should be a sub-module, derive from p2gcc sources

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2gui#1]
There are currently 2 versions of loadp2 sources... One in this repository and one in Dave Hein's p2gcc repository (https://github.com/davehein/p2gcc). Can the spin2gui repository include loadp2 sources as a sub-module to ensure both are kept in sync? There's a lot going on in P2 development at this time and keeping these as a single source could help Parallax forum users as they develop new tools.

Requirement: May need to have Dave Hein create a separate loadp2 repository from the p2gcc source repository.

**Comment by totalspectrum** [comment]
Yes, I don't really want to pull in the whole p2gcc repository just for loadp2. Also, it's entirely possible that spin2gui and p2gcc will have different requirements for loadp2, so I wouldn't be surprised to see the repositories drifting apart. That said, I would like to keep them in sync as much as possible, and if Dave makes loadp2 its own repository that would be a little bit easier.

**Comment by totalspectrum** [comment]
loadp2 is now its own repository. I think Dave Hein was planning to use my loadp2 repository in p2gcc as well.
