### ISSUE TITLE
Build error on macOS "cp: bin/fastspin: No such file or directory"...

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2gui#2]
Looks like the Makefile for macOS does not create the bin file required for copying fastspin & spin2cpp binaries... If I create the bin file before running the Makefile.mac (change its name to "Makefile", it completes as it normally does. I don't remember this being a problem in the past (pre 1231/2018).

The error:
gcc -g -Wall -I. -I./build -DFLEXSPIN_BUILD -o build/fastspin fastspin.c build/common.o build/spinc.o build/lexer.o build/symbol.o build/ast.o build/expr.o build/dofmt.o build/flexbuf.o build/lltoa_prec.o build/strupr.o build/strrev.o build/strdupcat.o build/preprocess.o build/cppexpr.o build/functions.o build/cse.o build/loops.o build/pasm.o build/outdat.o build/outlst.o build/spinlang.o build/basiclang.o build/clang.o build/outasm.o build/assemble_ir.o build/optimize_ir.o build/inlineasm.o build/outcpp.o build/cppfunc.o build/outgas.o build/directive.o build/expand.o build/mbchar.o build/mcpp_eval.o build/mcpp_main.o build/mcpp_system.o build/mcpp_support.o build/version.o build/spin.tab.o build/basic.tab.o build/cgram.tab.o -lm
cp spin2cpp/build/fastspin bin/fastspin
cp: bin/fastspin: No such file or directory
make: *** [bin/fastspin] Error 1

**Comment by totalspectrum** [comment]
I think this should be fixed now. Thanks for the bug report!
